CREATE DATABASE IF NOT EXISTS Banco;

CREATE TABLE IF NOT EXISTS ED (
	id int(3) NOT NULL AUTO_INCREMENT,
    pergunta VARCHAR(1000) NOT NULL,
    resposta VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS RC (
	id int(3) NOT NULL AUTO_INCREMENT,
    pergunta VARCHAR(1000) NOT NULL,
    resposta VARCHAR(1000) NOT NULL
);